version: '3.8'

services:
  trainer:
    build:
      context: .
      dockerfile: Dockerfile.trainer
    container_name: naivehub-trainer
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./Data:/app/Data
    networks:
      - naivehub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  classifier:
    build:
      context: .
      dockerfile: Dockerfile.classifier
    container_name: naivehub-classifier
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - TRAINER_URL=http://trainer:8001
    volumes:
      - models-volume:/app/models
    depends_on:
      - trainer
    networks:
      - naivehub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  models-volume:
    driver: local

networks:
  naivehub-network:
    driver: bridge
